### ISSUE TITLE
SoluteAmountDescriber review

### ISSUE THREAD

**Issue by zepumph** [phetsims/molarity#181]
- [x] `soluteAmountRegionChanged` is not private but is marked as such. Perhaps https://github.com/phetsims/molarity/issues/180 will fix this anyways.
- [x] concentrationDescriber is unused and should be removed as a parameter.
- [x] This line has hard coded numbers in it in it, and should probably use a range from a constants file (just like the bullet in #171). Perhaps here you can use `this.soluteAmountProperty.range` instead of calling over to a the constants file.
   ```js
   soluteAmount: Util.toFixed( Util.clamp( this.soluteAmountProperty.value, 0, 5.0 ), MolarityConstants.SOLUTE_AMOUNT_DECIMAL_PLACES )
    ```
    - [x] RE the same line above, why are we clamping the soluteAmountProperty to 5? Where did that number come from? I thought the soluteAmount only went from 0 to 1 moles?
- [x] I added this doc for this param: `* @param isCapitalized {boolean} - ignored if using quantitative descriptions`. Does this sound right? If so, I feel like it should be added where-ever it applies.
- [x] `getSoluteAmountState` is actually private.
- [x] Can we inline `getSoluteAmountState` to its only usage?
- [x] could we add an assertion to the `else` in `soluteAmountToIndex`?
- [x] The return typedef of `getSoluteAmountChangeStrings` needs some work. I originally mentioned it in #171, but since it lives here, I'll add an item here to for the todo in SoluteAmountDescriber.
- [x] `currentRegion` is a number, and should be renamed likely to "lastSoluteAmountRegionIndex" or something. This also likely applies to https://github.com/phetsims/molarity/issues/180

**Comment by zepumph** [comment]
>* @param isCapitalized {boolean} - ignored if using quantitative descriptions

I'm finding myself removing a fair number of these, because they don't apply to that particular `isCapitalized` parameter, for example `ConcentrationDescriber.getCurrentSolidsAmount` can be and is called regardless of the value of the quantitative descriptions Property.

**Comment by zepumph** [comment]
I feel good about checking off items if they are covered by another issue, so I checked off the last two.

**Comment by zepumph** [comment]
I review all the changes done to SoluteAmountDescriber so far, and feel good about them. Over to you to review my commits and close.

**Comment by twant** [comment]
Looks good! Closing.
