### ISSUE TITLE
Molarity - Master A11y Publication Checklist

### ISSUE THREAD

**Issue by emily-phet** [phetsims/molarity#99]
- [X]   @emily-phet "sign off" (2019 Quarter 4)
   - [x]  Performance acceptable
   - [x]  (Status unknown, moving on) Carefully review ?showPointerAreas
   - [x]  No new feature requests
- Pre-publication items
   - [x]  Main screenshot updated
  - [x]  Create issue for updating Teacher Guide (#220)
  - [x] Create issue for updating Sound Feature Video (#221)
     - [x] Sound Feature Video created/published
  - [x]  Verify credits
  - [x] Issue created to Update sim page credits to (https://github.com/phetsims/molarity/issues/228)
  - Finalize design docs 
     - [x] Interactive Description design doc (https://github.com/phetsims/molarity/issues/227)
     - [x] Sound design doc
 - [x] Create issue to do email announcement and Twitter announcement written, sent AP/ON (Date: / / ) (https://github.com/phetsims/molarity/issues/225)
- [x]   Post-publication items
- [x]  Add the simulation to responsible_dev.md
- [x]  Hold postmortem if applicable (Date: 03/02/2020)

## Implementation

- [x]   Repository created (Date: / /)
- [x]  simula-rasa used to create project skeleton
- [x]  README.md created using grunt unpublished-readme
- [x]  Collaborators added (such as QA team, designers, etc)
- [x]  standard GitHub label set applied
- [x]  repository added to chipper/data/ files
- [x]   Development started (Date: 01/29/2019 )
- [x]   Sound implementation in sim using Tambo complete (Date: 07/08/2019 by JB )
- [x]   Sim is "feature complete" (Date: 11/25/19)
- [x]   Preparation of [code for code review](https://github.com/phetsims/phet-info/blob/master/checklists/code_review_checklist.md) completed (Date: 08/29/19 by TW)
- [x]   Code review (likely by responsible dev) completed (Date: 12/10/19)
- [x]  Update implementation notes with a11y/description specific documentation (Date: 9/24/19)
- [x]   Published (Date: 2/17/20)
- [x]  README.md updated using grunt published-readme (in master and release branch)

## QA
- [x]   Dev testing started (Date: 10/07/2019)
- [x]   Dev testing completed (Date: 10/10/2019)
- [x]   First RC published (Date: 12/18/2019)
- [x]  Test matrices put in Testing Matrices Folder
- [x]   RC testing completed (Date: 2/14/20)
  - [x] RC Test - https://github.com/phetsims/QA/issues/464 completed (Jan 8, 2020)
  - [x] RC Test 1.5.0-rc.3 - https://github.com/phetsims/QA/issues/476 (closed Feb 10, 2020)

Published with interactive description (regular and mobile), sound effects and sonification, and alternative input - 2/17/2020

**Comment by emily-phet** [comment]
I just had a meeting with @jessegreenberg and @zepumph, and one of the topics I brought up was a walk-through of a potentially desirable workflow for Molarity. I wanted to share what came out of the conversation with everyone - see below.

- (MM and TW) Finalizing design/implementation (this is the stage we’re in now, ironing out the remaining kinks for design and implementation)
- (TW, with support as needed!) Preparation of code for code review - there’s a handy dandy checklist for this.
- Perhaps MK or JG is a good person to do code review? If not, will need to check in with Ariel about who might do this in advance to get this on their plate. 
- (??) Code review 

(JB) Implement sound in sim with Tambo (can happen in parallel with TW’s work listed above, just coordinate so as not to... step on each others code).

- (TW to lead, with support as needed) Dev test, address issues, iterate as needed
- (TW to lead, with support as needed) RC test, address issues, iterate as needed
- (TW) Publish!

Just as I was going to send this info as an email, it occurred to me that it might be useful to have this as a GitHub list, and of course (!) there is something similar that existed and had been adapted by @terracoda. So, I adapted it further for the list above. Please feel free to edit the list above as needed to make it more accurate and helpful. My hope is that this can serve as a useful tool for @twant and @Matthew-phet as they take their first sim to the finish line. :)

**Comment by pixelzoom** [comment]
Shouldn't "responsible developer" code review be somewhere on this checklist?

**Comment by zepumph** [comment]
To that seems like the obvious first choice, but it feels like a code review could be done by anyone so long as all parties are aware and agreed on it. I edited it above.

**Comment by pixelzoom** [comment]
It's not that I have a burning desire to do a code review :)  But I'm not entirely sure why you'd want the code review to be done by "anyone" when the responsible developer is presumably most familiar with the sim.  And I think it's also important for the responsible developer to keep current on what other developers are doing in the code that they're responsible for.   

Also related to this checklist and publication... There are also some non-A11y issues/changes that will be picked up as part of any publication that happens.  So we should also discuss who sheppards the sim through the RC and publication process.  That has typically been the responsible developer.

**Comment by ariel-phet** [comment]
@emily-phet @pixelzoom @zepumph I think it is totally appropriately for the responsible dev to be the code reviewer, and in case like this help shepherd the sim to publication (they don't need to be doing the publication work, but just helping avoid pitfalls and such).

**Comment by emily-phet** [comment]
The intention was not to exclude the responsible dev, rather - to not obligate the responsible dev. Their may be situations where the responsible dev is not available or would prefer not to do the code review, especially as we just keep making more and more sims! 

@pixelzoom you are of course welcome to code review this sim! We'll keep you in the loop as @twant gets ready for that step.

**Comment by zepumph** [comment]
@twant please feel free to fill in dates and check boxes above as things are finished. Let me know if I can help at all.

**Comment by terracoda** [comment]
@emily-phet and @jessegreenberg, I am not sure what to do with this issue. It's a bit different than the A11y Features checklist. I added the date for the completion of the first RC Test (https://github.com/phetsims/QA/issues/464). I think the sim is getting close to publication.

**Comment by emily-phet** [comment]
@terracoda Can you create issues for updating the Teacher Guide (assign to Brett and Amy) and for creating a sound features video (assign to Brett)? That's some of the remaining unchecked checkboxes at the top of the list above.

**Comment by jessegreenberg** [comment]
@emily-phet Molarity 1.5.0 has been published, does anything else need to be checked off here?

**Comment by emily-phet** [comment]
@jessegreenberg 
Wonderful news!
Let's hold a post-mortem (I'll send out a slack message on this) and then we can make some tweaks to this checklist (e.g., editing or completing the unchecked options above).

**Comment by emily-phet** [comment]
Issues have been created for all remaining checklist items above that we will be addressing. Please close this once all related issues are closed.

**Comment by terracoda** [comment]
Please re-assign me if I am supposed to focus on this issue.

**Comment by zepumph** [comment]
It looks like @BLFiedler and @Matthew-Moore240 are assigned to the outstanding issues, can this issue be closed and taken up in those side issues?

**Comment by terracoda** [comment]
I re-worded the unchecked items, so to be "create issue to..." that way I could check them, and those issues can be followed up in those issues. I think that is a good strategy going forward.

All things are checked and issues are made for undone items, so closing.
